### ISSUE TITLE
[Installing Question] In which folder write pip install wxPython?

### ISSUE THREAD

**Issue by amiremami** [Rakile/deforumation#1]
Hi, thanks for your great tool : )

I replaced your file with original deforum ones. Then opened Automatic1111 and nothing happened. I guess maybe I didn't install the wxpython?

In which folder I need to open cmd and write this command?

Also, in which section your UI will appear in Automatic1111? Should I install this script same as normal extension in automatic or download zip folder and replace the files?

Thanks

**Comment by lainollll** [comment]
No message in reddit.  Regards

Den fre 31 mars 2023 19:09amiremami ***@***.***> skrev:

**Comment by lainollll** [comment]
Working on a version that works regardless deforum version. It's getting updated regularly. And that makes it not working.

**Comment by KytraScript** [comment]
Whenever I click the "strength" setting in the deforumation GUI, it starts spamming the terminal with "Already Locked" and then crashes. Windows 10

**Comment by lainollll** [comment]
> Whenever I click the "strength" setting in the deforumation GUI, it starts spamming the terminal with "Already Locked" and then crashes. Windows 10
> 
> Edit: It happens if I click anything at all in the GUI

Trouble shooting
If the rendering shouldn't work (freezes), it might be because there is still a lock file that hasn't been released (C:\TEMP\prompt.txt.locked). This file is used in order for Deforum and Deforumation not to deadlock each-other. Just manually delete it if that should happen. Normally, you will see alot of "Waiting for lock file", in the command line interface that you started Automatic1111 from.

**Comment by KytraScript** [comment]
> 

I fixed it. I don't use the C: drive for my stable diffusion webui install and that breaks what your code is expecting. I submitted a PR to update the README.md with a small blurb about this issue in the troubleshooting section.
